const menu = [
  {
    id: 1,
    title: "Idli",
    category: "breakfast",
    price: 50,
    img: "./images/item1.jpg",
    desc: "Lorem ipsum description listed below",
  },
  {
    id: 2,
    title: "Dosa",
    category: "shakes",
    price: 60,
    img: "./images/item2.jpg",
    desc: "Lorem ipsum description listed below",
  },
  {
    id: 3,
    title: "Pancakes",
    category: "breakfast",
    price: 70,
    img: "./images/item3.jpg",
    desc: "Lorem ipsum description listed below",
  },
  {
    id: 4,
    title: "Omelette",
    category: "breakfast",
    price: 80,
    img: "./images/item4.jpg",
    desc: "Lorem ipsum description listed below",
  },
  {
    id: 5,
    title: "French Toast",
    category: "breakfast",
    price: 90,
    img: "./images/item5.jpg",
    desc: "Lorem ipsum description listed below",
  },
  {
    id: 6,
    title: "Burger",
    category: "lunch",
    price: 120,
    img: "./images/item6.jpg",
    desc: "Lorem ipsum description listed below",
  },
  {
    id: 7,
    title: "Pizza",
    category: "lunch",
    price: 150,
    img: "./images/item7.jpg",
    desc: "Lorem ipsum description listed below",
  },
  {
    id: 8,
    title: "Pasta",
    category: "snack",
    price: 130,
    img: "./images/item8.jpg",
    desc: "Lorem ipsum description listed below",
  },
  {
    id: 9,
    title: "Salad",
    category: "snack",
    price: 100,
    img: "./images/item9.jpg",
    desc: "Lorem ipsum description listed below",
  },
  {
    id: 10,
    title: "Sandwich",
    category: "lunch",
    price: 110,
    img: "./images/item10.jpg",
    desc: "Lorem ipsum description listed below",
  },
]

export default menu
